local registry = require("codex.providers")

describe("codex.providers registry", function()
  before_each(function()
    registry.reset()
  end)

  describe("resolve", function()
    it("resolves 'native' to native provider", function()
      local provider, name = registry.resolve("native")
      assert.is_not_nil(provider)
      assert.equals("native", name)
      assert.is_function(provider.open)
      assert.is_function(provider.close)
      assert.is_function(provider.send)
      assert.is_function(provider.focus)
      assert.is_function(provider.toggle)
      assert.is_function(provider.is_alive)
      assert.is_function(provider.is_available)
      assert.is_function(provider.get_bufnr)
    end)

    it("resolves 'none' to none provider", function()
      local provider, name = registry.resolve("none")
      assert.is_not_nil(provider)
      assert.equals("none", name)
    end)

    it("resolves 'auto' to native when snacks is unavailable", function()
      local provider, name = registry.resolve("auto")
      assert.is_not_nil(provider)
      -- In test env, snacks is not installed, so should fall back to native
      assert.equals("native", name)
    end)

    it("errors on unknown provider", function()
      assert.has_error(function()
        registry.resolve("nonexistent")
      end)
    end)

    it("errors when provider is not available", function()
      assert.has_error(function()
        registry.resolve("external")
      end)
    end)
  end)
end)
